kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: dms-tst
  name: dms-route
  labels:
    app: dms
spec:
  to:
    kind: Service
    name: dms-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
