kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: ctie-tst
  name: ctie-route
  labels:
    app: ctie
spec:
  to:
    kind: Service
    name: ctie-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
