kind: Service
apiVersion: v1
metadata:
  namespace: first-ms-tst
  name: first-ms-service
  labels:
    app: first-ms
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: first-ms