kind: Service
apiVersion: v1
metadata:
  namespace: christopher-tst
  name: christopher-service
  labels:
    app: christopher
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: christopher