kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: erp-api-tst
  name: erp-api-route
  labels:
    app: erp-api
spec:
  to:
    kind: Service
    name: erp-api-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
