kind: Service
apiVersion: v1
metadata:
  namespace: {{ocp-namespace}}
  name: git4u-service
  labels:
    app: git4u
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: git4u