kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: lns-tst
  name: lns-route
  labels:
    app: lns
spec:
  to:
    kind: Service
    name: lns-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
