kind: Service
apiVersion: v1
metadata:
  namespace: register-api-tst
  name: register-api-service
  labels:
    app: register-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: register-api